### ISSUE TITLE
Use PostCSS API

### ISSUE THREAD

**Issue by ai** [UXtemple/autoprefix#1]
PostCSS already has awesome CSS parser, so you do not need even to parse CSS again.

``` js
postcss([autoprefixer]).process(css).root // Root node
```

**Comment by ai** [comment]
BTW, next PostCSS 4.2 will support custom syntax. So maybe we could create `postcss-react` to process any React Object by any PostCSS plugins?

We can write some “parser” (just transform React Style object to PostCSS objects) and “stringifier” (transform them back to object) so we can do it very fast.

**Comment by dariocravero** [comment]
Thanks @ai :) Fix pushed ;).

It would be amazing to go ahead with that plugin.
As a matter of fact, it can be generic enough, as in, it should take an object and output a prefixed object. React doesn't add anything to it.

The only issue I have with PostCSS >= 4.1 is that it implements an asynchronous plugin API which doesn't work with [babel-plugin-react-autoprefix](https://github.com/UXtemple/babel-plugin-react-autoprefix) because of babel walker's nature.
Hopefully async will be supported by then :)

**Comment by ai** [comment]
Can you tell me more about async problem. Maybe some code examples?
